#!/bin/env python3

# --------------------------------------------------------------
# File: rpcgenerate
# Author: Serena GIbbons
# --------------------------------------------------------------

import argparse
import os
import re
import json
import subprocess

IDL_TO_JSON_EXECUTABLE = "./idl_to_json"

TYPE_OF_TYPES = ["builtin", "struct", "array"]
BUILTIN_TYPES = ["void", "int", "float", "string"]

def idl_to_json(filename):
    """
    Create the JSON representation of the IDL file using idl_to_json.cpp and
    return the parsed ddeclarations in a Python dictionary 
    """
    # Make sure IDL file exists and is readable
    assert os.path.isfile(filename), f"Path {filename} does not designate a file"
    assert os.access(filename, os.R_OK), f"File {filename} is not readable" 

    # Make sure idl_to_json exists and is executable
    assert os.path.isfile(IDL_TO_JSON_EXECUTABLE), f"Path {IDL_TO_JSON_EXECUTABLE} does not designate a file...run \"make\" to create it" 
    assert os.access(IDL_TO_JSON_EXECUTABLE, os.X_OK), f"File {IDL_TO_JSON_EXECUTABLE} exists but is not executable"

    # Parse declarations into a Python dictionary
    decls = json.loads(subprocess.check_output([IDL_TO_JSON_EXECUTABLE, filename]))
    
    return decls

def generate_headers(idl_filename, file_type):
    """
    Generate the list of header files and namespaces to include
    """
    header_files = (
        "#include <string>\n"
        "using namespace std;\n"
        "#include <iostream>\n"
        "#include <vector>\n"
        "#include <cstring>\n"
        "#include <cstdio>\n"
        "#include \"" + idl_filename +"\"\n"
        "#include \"rpc" + file_type + "helper.h\"\n"
        "#include \"c150debug.h\"\n"
        "#include \"buffer.h\"\n"
        "#include \"serializer.h\"\n"
        "#include \"deserializer.h\"\n"
        "using namespace C150NETWORK;\n")
   
    return header_files

def generate_proxy(decls):
    """
    Generate the proxy code
    """
    remote_functions = ""
    type_set, struct_info = get_type_set(decls)
    print("type_set:")
    print(type_set)
    print("struct_info:")
    print(struct_info)
    functions = decls["functions"]

    serializers, serializer_contract, deserializers, deserializer_contract = generate_serializers_and_deserializers(
        type_set, struct_info, "proxy")
    
    remote_functions += (serializer_contract + deserializer_contract + serializers + deserializers)

    for name, sig in functions.items():
        args = sig["arguments"]
        return_type = sig["return_type"]
        remote_functions += generate_remote_function(name, args, return_type)

    return remote_functions

def generate_remote_function(function_name, args, return_type):
    """
    Generate the remote function
    """
    # Build argument string and serialization function calls
    arg_string_list = []
    serialize_calls = []
    
    for arg in args:
        arg_type = arg["type"]
        arg_name = arg["name"]

        if '[' in arg_type:
            # Handle array types
            inner_type, size_brackets = parse_array(arg_type)
            arg_declaration = f"{inner_type} {arg_name}{size_brackets}"
            # Normalize the argument type for serialization function naming
            normalized_type = arg_type.replace('][', '_').replace('[', '_').replace(']', '_')
            serializer_call = f"serialize{normalized_type}(&b, {arg_name});"
        else:
            # Handle non-array types
            arg_declaration = f"{arg_type} {arg_name}"
            serializer_call = f"serialize(&b, {arg_name});"
            
        #arg_declaration, serializer_call = parse_argument(arg)
        arg_string_list.append(arg_declaration)
        serialize_calls.append(serializer_call)

    arg_string = ", ".join(arg_string_list)
    serialize_args = "\n\t".join(serialize_calls)

    # Determine function ending based on return type
    if return_type in {"string", "int", "float"}:
        end = (f"\t{return_type} result = deserialize{return_type.capitalize()}(RPCPROXYSOCKET);\n"
               "\treturn result;\n")
    elif return_type == "void":
        end = ("\tstring result = deserializeString(RPCPROXYSOCKET);\n"
                 "\tif (result.compare(\"DONE\") != 0) {\n"
                 "\t\tthrow C150Exception("
                 f"\"{function_name}() received invalid response from the server\");\n"
                 "\t}\n")
    else:
        end = f"\t{return_type} res;\n\tdeserialize{return_type}(&res);\n\treturn res;\n"

    # Construct the function body
    body = (f"\tBuffer b;\n"
              f"\tserialize(&b, \"{function_name}\");\n"
              f"\t{serialize_args}\n"
              f"\tRPCPROXYSOCKET->write(b.buf, b.length);\n"
              f"\tb.reset();\n"
              f"{end}")

    # Construct the complete remote function
    remote_function = (f"{return_type} {function_name}({arg_string}) {{\n"
                       f"{body}}}\n")

    return remote_function

def generate_stub(decls):
    """
    Generates stub code for the given functions.
    """
    stub_code = ""
    dispatcher_deserializers = ""
    functions = decls["functions"]
    type_set, struct_info = get_type_set(decls)

    serializers, serializer_contract, deserializers, deserializer_contract = generate_serializers_and_deserializers(
        type_set, struct_info, "stub")
    
    stub_code += (serializer_contract + deserializer_contract + serializers + deserializers)

    for name, sig in functions.items():
        args = sig["arguments"]
        return_type = sig["return_type"]

        # Generate local function for each RPC function
        stub_code += generate_local_functions(name, args, return_type)

        # Generate argument deserialization and dispatcher logic
        arg_names = ", ".join([arg["name"] for arg in args])
        arg_deserializers = ""

        for arg in args:
            arg_type = arg["type"]
            if arg_type in {"string", "int", "float"}:
                arg_deserializers += (
                    f"\t\t\t{arg_type} {arg['name']} = deserialize{arg_type.capitalize()}(RPCSTUBSOCKET);\n"
                )
            elif '[' in arg_type: # Array
                arg_inner_type, arg_size_bracket = parse_array(arg_type)
                arg_deserializers += (
                    f"\t\t\t{arg_inner_type} {arg['name']}{arg_size_bracket};\n"
                    f"\t\t\tdeserialize{arg['type'].replace('][', '_').replace(']', '_').replace('[', '_')}({arg['name']});\n"
                )
            else: # Struct
                arg_deserializers += (
                    f"\t\t\t{arg['type']} {arg['name']};\n"
                    f"\t\t\tdeserialize{arg['type'].replace('][', '_').replace(']', '_').replace('[', '_')}(&({arg['name']}));\n"
                )

        # Call the corresponding local function
        arg_deserializers += f"\t\t\t__{name}({arg_names});\n"
        dispatcher_deserializers += (
            f"\t\telse if (func_name == \"{name}\") {{\n"
            f"{arg_deserializers}\t\t}}\n"
        )

    # Dispatcher function body
    dispatcher_body = (
        "\tif (!RPCSTUBSOCKET->eof()) {\n"
        "\t\tstring func_name = deserializeString(RPCSTUBSOCKET);\n"
        "\t\tif (func_name.compare(\"\") == 0) return;\n"
        f"{dispatcher_deserializers}"
        "\t\telse {\n"
        "\t\t\tthrow C150Exception(\"Error: invalid function.\");\n"
        "\t\t}\n"
        "\t}\n"
    )

    # Complete dispatcher function
    dispatcher = f"void dispatchFunction() {{\n{dispatcher_body}}}\n"
    stub_code += dispatcher

    return stub_code

def parse_array(arg_type):
    """
    Parses array type arguments to extract inner type and size.
    """
    arg_type_clean = arg_type.lstrip('_')
    arg_inner_type = arg_type_clean.split('[', 1)[0]
    arg_size_bracket = '[' + arg_type_clean.split('[', 1)[1]
    return arg_inner_type, arg_size_bracket

def generate_local_functions(function_name, args, return_type):
    """
    Generates the local function stub for an RPC function.
    """
    arg_string = ""
    arg_names = ", ".join([arg["name"] for arg in args])

    # Build argument list for the function signature
    for i, arg in enumerate(args):
        arg_type = arg["type"]
        arg_name = arg["name"]

        if '[' in arg_type:  # Handle array types
            arg_inner_type, arg_size_bracket = parse_array(arg_type)
            arg_string += f"{', ' if i > 0 else ''}{arg_inner_type} {arg_name}{arg_size_bracket}"
        else:
            arg_string += f"{', ' if i > 0 else ''}{arg_type} {arg_name}"

    # Generate function call and serialization logic
    if return_type == "void":
        function_call = f"\t{function_name}({arg_names});\n\tstring result = \"DONE\";\n"
    else:
        function_call = f"\t{return_type} result = {function_name}({arg_names});\n"

    # Function body
    body = (
        "\tBuffer b;\n"
        "\tserialize(&b, result);\n"
        "\tRPCSTUBSOCKET->write(b.buf, b.length);\n"
        "\tb.reset();\n"
    )

    # Combine into the local function definition
    local_function = (
        f"void __{function_name}({arg_string}) {{\n"
        f"{function_call}"
        f"{body}}}\n"
    )

    return local_function

def get_type_set(decls):
    """
    Extract types from function arguments, return types, and structs, including struct members.
    
    Returns:
        tuple: A set of types, and a list of struct details (names and members).
    """
    type_set = set()  # Set to store unique types
    struct_arr = []   # List to store details of structs
    functions = decls["functions"]
    types = decls["types"]

    # Process function declarations
    for func_name, func_sig in functions.items():
        # Add argument types to the type set
        for arg in func_sig["arguments"]:
            type_set.add(arg["type"])
        # Add return type to the type set
        type_set.add(func_sig["return_type"])

    # Process type declarations (structs and arrays)
    for type_name, type_sig in types.items():
        type_of_type = type_sig["type_of_type"]

        if type_of_type == "struct":
            # Add struct name to the type set
            type_set.add(type_name)
            
            # Gather struct member details
            struct_details = {"struct_name": type_name, "mem_name": [], "mem_type": []}
            for member in type_sig["members"]:
                type_set.add(member["type"])  # Add member type to the type set
                struct_details["mem_name"].append(member["name"])
                struct_details["mem_type"].append(member["type"])

            struct_arr.append(struct_details)

        elif type_of_type == "array":
            # Add array name and its member type to the type set
            type_set.add(type_name)
            type_set.add(type_sig["member_type"])

    return type_set, struct_arr


def generate_serializers_and_deserializers(type_set, struct_info, file_type):
    """
    Generate serializer and deserializer functions and forward declarations.
    """
    serializers = ""
    serializer_contracts = ""
    deserializers = ""
    deserializer_contracts = ""

    for type_of_type in type_set:
        if type_of_type not in BUILTIN_TYPES:
            # Arrays
            if type_of_type.startswith("__"):
                serializer, serializer_contract = generate_array_serializer(type_of_type)
                serializers += serializer
                serializer_contracts += serializer_contract
                deserializer, deserializer_contract = generate_array_deserializer(type_of_type, file_type)
                deserializers += deserializer
                deserializer_contracts += deserializer_contract
            # Structs
            else:
                serializer, serializer_contract = generate_struct_serializer(type_of_type, struct_info)
                serializers += serializer
                serializer_contracts += serializer_contract
                deserializer, deserializer_contract = generate_struct_deserializer(type_of_type, struct_info, file_type)
                deserializers += deserializer
                deserializer_contracts += deserializer_contract
    
    return serializers, serializer_contracts, deserializers, deserializer_contracts

def generate_struct_serializer(type_of_type, struct_info):
    """
    Generate function to serialize a struct.
    """
    serializer_body = ""
    for struct in struct_info:
        if struct["struct_name"] == type_of_type:
            for mem_name, mem_type in zip(struct["mem_name"], struct["mem_type"]):
                serializer_body += f"\tserialize(b, {type_of_type[0]}1.{mem_name});\n"

    serializer = f"void serialize(Buffer *b, {type_of_type} {type_of_type[0]}1) {{\n{serializer_body}}}\n"
    serializer_contract = f"void serialize(Buffer *b, {type_of_type} {type_of_type[0]}1);\n"
    
    return serializer, serializer_contract

def generate_struct_deserializer(type_of_type, struct_info, file_type):
    """
    Generate function to deserialize a struct.
    """
    var = f"{type_of_type[0]}1"
    deserializer_body = ""
    for struct in struct_info:
        if struct["struct_name"] == type_of_type:
            for mem_name, mem_type in zip(struct["mem_name"], struct["mem_type"]):
                if mem_type in {"string", "int", "float"}:
                    deserializer_body += f"\t{var}->{mem_name} = deserialize{mem_type.capitalize()}(RPC{file_type.upper()}SOCKET);\n"
                else:
                    formatted_mem_type = mem_type.replace('][', '_').replace('[', '_').replace(']', '_')
                    if '[' in mem_type:
                        deserializer_body += f"\tdeserialize{formatted_mem_type}({var}->{mem_name});\n"
                    else:
                        deserializer_body += f"\tdeserialize{formatted_mem_type}(&({var}->{mem_name}));\n"

    deserializer = f"void deserialize{type_of_type} ({type_of_type} *{var}) {{\n{deserializer_body}}}\n"
    deserializer_contract = f"void deserialize{type_of_type} ({type_of_type} *{var});\n"
    
    return deserializer, deserializer_contract


def generate_array_serializer(array_type):
    """
    Generate function to serialize an array.
    """
    # Extract size dimensions and type information
    array_sizes_string = '[' + array_type.split('[', 1)[1]  # Extract dimensions in [10][5] format
    normalized_type = array_type.replace('][', '_').replace('[', '_').replace(']', '_')
    base_type = next(s for s in normalized_type.split('_') if s.isalpha())  # Extract the base type (e.g., int)
    array_sizes = [int(s) for s in normalized_type.split('_') if s.isdigit()]  # Extract dimensions as integers

    # Generate the serializer body
    serializer_body = ""
    nested_loops_vars = []
    tab = ""
    
    for idx, size in enumerate(array_sizes):
        loop_var = f"i{idx}"  # Variable for the loop
        nested_loops_vars.append(loop_var)
        serializer_body += f"{tab}\tfor (int {loop_var} = 0; {loop_var} < {size}; {loop_var}++) {{\n"
        tab += "\t"  # Increase indentation for nested loops

    # Construct the array variable indexing (e.g., arr[i0][i1])
    array_indexing = ''.join(f"[{var}]" for var in nested_loops_vars)
    serializer_body += f"{tab}\tserialize(b, arr{array_indexing});\n"

    # Close the nested loops
    for _ in array_sizes:
        serializer_body += f"{tab}}}\n"
        tab = tab[:-1]  # Reduce indentation

    # Generate the full serializer function and its declaration
    serializer_function = (
        f"void serialize{normalized_type}(Buffer *b, {base_type} arr{array_sizes_string}) {{\n"
        f"{serializer_body}}}\n"
    )
    serializer_declaration = (
        f"void serialize{normalized_type}(Buffer *b, {base_type} arr{array_sizes_string});\n"
    )

    return serializer_function, serializer_declaration

def generate_array_deserializer(type_of_type, file_type):
    """
    Generate function to deserialize an array.
    """
    # Extract array size and clean type representation
    arr_sizes_string = f"[{type_of_type.split('[', 1)[1]}"
    type_of_type = type_of_type.replace('][', '_').replace('[', '_').replace(']', '_')

    # Extract array type and sizes
    arr_type = [s for s in type_of_type.split('_') if s.isalpha()][0]
    arr_sizes = [int(s) for s in type_of_type.split('_') if s.isdigit()]

    idx = 0
    tab = ""
    deserializer_body = ""
    vars_list = []

    # Generate deserializer loops for array sizes
    for size in arr_sizes:
        var = f"i{idx}"
        vars_list.append(var)
        deserializer_body += f"{tab}\tfor (int {var} = 0; {var} < {size}; {var}++) {{\n"
        idx += 1
        tab += "\t"

    # Generate the deserialization for the array elements
    arr_vars_string = ''.join([f"[{var}]" for var in vars_list])
    if arr_type in {"string", "float", "int"}:
        deserializer_body += f"{tab}\tarr{arr_vars_string} = deserialize{arr_type.capitalize()}(RPC{file_type.upper()}SOCKET);\n"
    else:  # Struct type
        deserializer_body += f"{tab}\tdeserialize{arr_type}(&(arr{arr_vars_string}));\n"

    # Close array size loops
    for _ in arr_sizes:
        deserializer_body += f"{tab}}}\n"
        tab = tab[:-1]

    # Generate full deserializer function and its contract
    deserializer = f"void deserialize{type_of_type}({arr_type} arr{arr_sizes_string}) {{\n{deserializer_body}}}\n"
    deserializer_contract = f"void deserialize{type_of_type}({arr_type} arr{arr_sizes_string});\n"

    return deserializer, deserializer_contract

def main():
    """
    Generate the RPC proxy and stub files from the given idl file.
    Command line: python rpcgenerate <idl_filepath>
    """
    # Parse arguments
    parser = argparse.ArgumentParser()
    parser.add_argument('idl_filepath')
    args = parser.parse_args()

    # Set idl file path
    idl_filepath = args.idl_filepath
    idl_filename = os.path.basename(idl_filepath)

    # Parse declarations into a Python dictionary
    decls = idl_to_json(idl_filepath)
    json_string = json.dumps(decls, indent=4)
    print(json_string)

    # Set proxy and stub file names
    proxy_filename = re.sub(r'\.idl', '.proxy.cpp', idl_filename)
    stub_filename = re.sub(r'\.idl', '.stub.cpp', idl_filename)

    # Generate the header files and namespaces
    proxy_headers = generate_headers(idl_filename, 'proxy')
    stub_headers = generate_headers(idl_filename, 'stub')

    # Generate code
    proxy_code = generate_proxy(decls)
    stub_code = generate_stub(decls)

    print(proxy_filename + ":\n" + proxy_code)
    print(stub_filename + ":\n" +stub_code)

    # Write the proxy code to the proxy file
    with open(proxy_filename, "w") as f:
        f.writelines([proxy_headers, proxy_code])

    # Write the stub code to the stub file
    with open(stub_filename, "w") as f:
        f.writelines([stub_headers, stub_code])

if __name__=="__main__":
	main()